services:
  ipfsproxy:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - data:/usr/src/app/data

  ipfs:
    image: ipfs/kubo:v0.29.0
    restart: unless-stopped
    env_file:
      - .env
    command: "daemon --migrate=true --agent-version-suffix=docker --enable-gc"
    volumes:
      - ipfs:/data/ipfs
      - ./001-init.sh:/container-init.d/001-init.sh

volumes:
  data:
  ipfs:
