services:
  ipfsproxy:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - data:/usr/src/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ipfsproxy.rule=Host(`ipfsproxy.teia.art`, `ipfsproxy.teia.rocks`)"
      - "traefik.http.routers.ipfsproxy.tls=true"
      - "traefik.http.routers.ipfsproxy.tls.certresolver=cloudflare"
      - "traefik.http.routers.ipfsproxy.middlewares=hsts-headers@file,traefik-real-ip@file,cors@file,limit@file"
      - "traefik.http.services.ipfsproxy.loadbalancer.server.port=4444"

  ipfs:
    image: ipfs/kubo:v0.28.0
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ipfs:/data/ipfs
      - ./001-init.sh:/container-init.d/001-init.sh

volumes:
  data:
  ipfs:
